"""
Story concepts library for narrative_ambient_story Reels -- 27 real places whose real
history is dramatised across three 10-second beats, carried by Flow's own diegetic
ambience instead of narration.

Every entry is a documented, publicly known place. `real_basis` records the factual
claim each Reel rests on, so metadata written from a concept stays true to the history
rather than inventing one. Keep it accurate when adding concepts: no speculative death
tolls, no invented events, no attributing a place's decline to a cause historians do not.

StoryConcept extends ConceptDefinition rather than replacing it, so the existing
diversity ranking, manifest round-trip, and concept-slug rebuild all keep working
unchanged. The inherited fields carry story meaning:

    environments   -> the place as it lived, before the turn
    architectures  -> its built identity
    transformations-> the turn itself (the eruption, the evacuation, the sand)
    reveals        -> what a camera finds there today
"""
from dataclasses import dataclass, field
from typing import Dict, List

from .concepts import ConceptDefinition


@dataclass
class StoryConcept(ConceptDefinition):
    """A real place, its documented history, and the ambience each beat should carry."""

    # Factual anchor. Never publish a claim this does not support.
    real_basis: str = ""

    # Diegetic sound design per beat, handed to Flow as a positive instruction.
    # Keys: "before", "turn", "after". Never speech -- see StoryPlanner.NEGATIVE_EXCLUSIONS.
    ambient_sounds: Dict[str, str] = field(default_factory=dict)

    # Which kind of story this is, so metadata cannot claim the wrong one. Titles are
    # written per frame: "Why Nobody Lives Here Anymore" is false for Gobekli Tepe, which
    # was never a settlement, and for Lalibela, which is still in use today.
    #   "abandonment" -- people left a place they lived in
    #   "burial"      -- nature or human hands covered it over
    #   "vanishing"   -- the water, not the people, went away
    #   "creation"    -- the story is how it came to exist
    narrative_frame: str = "abandonment"


STORY_CONCEPTS: List[StoryConcept] = [
    StoryConcept(
        id_slug="pompeii",
        narrative_frame="burial",
        name="Pompeii",
        category_group="Buried by Nature",
        real_basis="Roman city near Naples buried under volcanic ash and pumice when Mount Vesuvius erupted in AD 79; excavations since 1748 have uncovered streets, houses and frescoes preserved by the ash.",
        environments=["a busy Roman street lined with painted shopfronts", "a stone-paved forum beneath a clear summer sky", "a colonnaded courtyard house with a garden pool"],
        architectures=["terracotta-roofed Roman townhouses and columned public forum", "frescoed villa interiors opening onto peristyle gardens"],
        transformations=["a towering ash column rising over the mountain, then grey pumice falling like snow until roofs vanish and the street disappears under drifts", "daylight dimming to brown as ash buries doorways, statues and paving stones metre by metre"],
        camera_styles=["slow forward dolly down the street, holding the same axis through all three beats", "steady low crane rise over rooftops keeping the mountain on the horizon"],
        lighting_schemes=["bright Mediterranean midday turning to ochre gloom under falling ash", "warm morning sun draining to grey overcast"],
        materials=["volcanic tuff blockwork", "painted lime plaster", "terracotta roof tiles", "grey compacted ash"],
        reveals=["the same street excavated and empty, walls standing roofless under open sky, ash-grey stone in clean archaeological light", "silent paved roads and doorless thresholds preserved exactly where the ash left them"],
        default_title="Pompeii",
        topic_description="A living Roman street buried by Vesuvius in AD 79 and uncovered again centuries later",
        ambient_sounds={
            "before": "warm daytime town ambience: distant market murmur without intelligible words, cart wheels on stone, sparrows, a trickling fountain",
            "turn": "deep volcanic rumble, dense pattering of falling pumice on tile roofs, wind rising, sound dulling as ash muffles the world",
            "after": "open silence, thin wind across roofless stone walls, one distant bird, faint grit shifting underfoot",
        },
    ),
    StoryConcept(
        id_slug="herculaneum",
        narrative_frame="burial",
        name="Herculaneum",
        category_group="Buried by Nature",
        real_basis="Seaside Roman town destroyed by pyroclastic flows from Vesuvius in AD 79; buried far deeper than Pompeii, which carbonised and preserved wooden beams, furniture and scrolls.",
        environments=["a seafront terrace of Roman boathouses above a calm bay", "a narrow shaded lane of two-storey homes with wooden balconies"],
        architectures=["multi-storey seaside villas with timber balconies and vaulted boat chambers", "compact brick-faced townhouses with mosaic thresholds"],
        transformations=["a searing grey surge pouring down the mountainside and over the shoreline, engulfing balconies and vaults in seconds, timber darkening to charcoal", "successive hot flows sealing the town beneath tens of metres of solidifying volcanic rock"],
        camera_styles=["locked wide shot facing the shoreline, unchanged framing across all three beats", "slow lateral track along the terrace front"],
        lighting_schemes=["clear coastal afternoon light collapsing to opaque grey", "low sun on water fading to ashen darkness"],
        materials=["volcanic rock crust", "carbonised timber beams", "coloured floor mosaic", "sea-worn brick"],
        reveals=["the excavated town sunk in a deep stone trench, blackened beams still in place, modern city walls rising far above the rim", "vaulted boat chambers open to the air, dark carbonised wood intact after two millennia"],
        default_title="Herculaneum",
        topic_description="A Roman seaside town sealed by pyroclastic flow in AD 79, its timber preserved as charcoal",
        ambient_sounds={
            "before": "gentle harbour ambience: small waves against stone, rigging creaking, gulls, faint distant voices with no discernible words",
            "turn": "escalating low roar, sharp crackle of superheated air, wood splitting, then abrupt heavy muffling",
            "after": "still air in a deep stone pit, faint drip of water, distant modern traffic far above",
        },
    ),
    StoryConcept(
        id_slug="kolmanskop",
        narrative_frame="burial",
        name="Kolmanskop",
        category_group="Buried by Nature",
        real_basis="German diamond-mining town in the Namib Desert, founded 1908 and largely abandoned by the 1950s after richer deposits were found further south; drifting sand has since filled its houses.",
        environments=["a neat colonial street of pastel houses with a ballroom and tram line", "manicured desert-edge gardens beside imported European facades"],
        architectures=["German colonial townhouses with tall shuttered windows and pitched roofs", "grand ballroom and theatre with panelled interiors"],
        transformations=["the town emptying, doors left ajar, then desert wind pushing fine orange sand through hallways until dunes climb the interior walls", "sand drifts rising room by room, sunlight moving across dunes indoors where furniture used to stand"],
        camera_styles=["slow forward push through a doorway into an interior room, identical axis in every beat", "steady low tracking shot along the street facade"],
        lighting_schemes=["hard bright desert sun with crisp shadows through window frames", "warm low-angle light raking across interior sand"],
        materials=["painted plaster walls", "peeling wallpaper", "fine orange desert sand", "weathered timber frames"],
        reveals=["the same room half-filled with a smooth sand dune, doorframe standing above the drift, sunlight through a broken window", "an entire street of houses with sand pouring out of their doorways"],
        default_title="Kolmanskop",
        topic_description="A Namib diamond town abandoned in the 1950s and slowly filled by desert sand",
        ambient_sounds={
            "before": "quiet colonial-town ambience: a distant tram bell, wind in shutters, faint piano from indoors, desert insects",
            "turn": "rising desert wind, sand hissing across floorboards and grinding under doors, shutters banging, sound thinning as rooms fill",
            "after": "steady dry wind through empty window frames, sand trickling, a loose shutter knocking",
        },
    ),
    StoryConcept(
        id_slug="plymouth-montserrat",
        narrative_frame="burial",
        name="Plymouth, Montserrat",
        category_group="Buried by Nature",
        real_basis="Capital of Montserrat, buried by pyroclastic flows and ash from the Soufriere Hills volcano between 1995 and 1997 and permanently evacuated; it remains an abandoned capital inside an exclusion zone.",
        environments=["a small Caribbean capital of bright colonial buildings above a harbour", "a green hillside town with a clock tower and market square"],
        architectures=["pastel Caribbean colonial civic buildings with verandas", "corrugated-roof homes stepping up a green volcanic slope"],
        transformations=["ash falling steadily over rooftops, then grey pyroclastic flows sliding down the valley and filling streets to first-floor height", "the harbour turning grey as the town is buried and the green hillside erased"],
        camera_styles=["high wide shot over the town toward the volcano, framing unchanged in all beats", "slow descent toward the clock tower"],
        lighting_schemes=["vivid tropical sunlight fading to smothered grey", "green Caribbean daylight replaced by ash-filtered haze"],
        materials=["painted concrete render", "corrugated metal roofing", "grey volcanic ash and mud", "tropical vegetation"],
        reveals=["rooftops and a clock tower protruding from a flat grey ash plain, the volcano still steaming behind", "a buried capital with only upper storeys visible, no roads left"],
        default_title="Plymouth, Montserrat",
        topic_description="A Caribbean capital buried by volcanic flows in the 1990s and never reoccupied",
        ambient_sounds={
            "before": "warm Caribbean town ambience: tree frogs, distant surf, corrugated roofs ticking in the sun, birdsong",
            "turn": "deep volcanic roar building, ash raining on metal roofs, a hot rushing surge, then heavy muffled quiet",
            "after": "wind over a flat ash plain, faint steam venting, no birds",
        },
    ),
    StoryConcept(
        id_slug="skara-brae",
        narrative_frame="burial",
        name="Skara Brae",
        category_group="Buried by Nature",
        real_basis="Neolithic settlement on Orkney, Scotland, occupied around 3180-2500 BC and buried by sand for millennia; a severe storm in 1850 stripped the dunes and exposed the stone houses and their built-in furniture.",
        environments=["a low cluster of turf-covered stone dwellings above a windswept northern bay", "a grassy coastal headland with smoke rising from sunken roofs"],
        architectures=["semi-subterranean drystone houses linked by covered passages", "stone-slab beds, dressers and hearths built into the walls"],
        transformations=["the settlement falling quiet, then centuries of blown sand and grass sealing the roofs into a smooth green mound", "an 1850 storm tearing the dune open and stripping sand from the stone walls beneath"],
        camera_styles=["slow orbit around the settlement mound, same radius in every beat", "low forward creep along a covered stone passage"],
        lighting_schemes=["pale northern daylight with fast-moving cloud shadow", "cold storm light breaking into clear grey morning"],
        materials=["flagstone drystone walling", "turf and midden roofing", "wind-blown coastal sand", "wet dark stone"],
        reveals=["roofless stone rooms open to the sky, stone dressers and hearths still standing exactly in place, ocean behind", "the excavated village exposed on the shoreline, sand cut away around its walls"],
        default_title="Skara Brae",
        topic_description="A Neolithic Orkney village buried by sand for 4,000 years and uncovered by a storm in 1850",
        ambient_sounds={
            "before": "northern coastal ambience: constant sea wind, waves on rock, fire crackling in a stone hearth, seabirds",
            "turn": "wind rising to a gale, sand hissing over turf, surf pounding, then long muffled quiet under sand",
            "after": "clean hard wind across open stone, waves, oystercatcher calls",
        },
    ),
    StoryConcept(
        id_slug="gobekli-tepe",
        narrative_frame="burial",
        name="Gobekli Tepe",
        category_group="Buried by Nature",
        real_basis="Monumental stone enclosures in southeastern Turkiye built around 9500-8000 BC, predating pottery, metal and the wheel; the site was deliberately backfilled in antiquity and rediscovered by excavation from 1995.",
        environments=["a bare limestone ridge overlooking rolling plains", "a hilltop of circular enclosures under an enormous open sky"],
        architectures=["rings of T-shaped limestone pillars carved with animal reliefs", "drystone enclosure walls with monolithic central pillars"],
        transformations=["the enclosures falling out of use, then being deliberately filled in with rubble and earth by hand until the pillars vanish", "the hill rounding into an ordinary grassy mound as centuries of soil settle over it"],
        camera_styles=["rising crane over the enclosure rings, identical arc in each beat", "slow push toward a central T-pillar"],
        lighting_schemes=["low golden Anatolian sun casting long pillar shadows", "hard midday light flattening into dusty haze"],
        materials=["carved limestone monoliths", "drystone rubble fill", "dry red earth", "sparse grass"],
        reveals=["excavated enclosures reopened beneath a modern shelter roof, carved animals sharp on the pillars after 11,000 years", "the ridge cut open in terraces, stone rings exposed side by side"],
        default_title="Gobekli Tepe",
        topic_description="The world's oldest known monumental enclosures, deliberately buried in antiquity and dug out again",
        ambient_sounds={
            "before": "high open-plain wind, stone being struck rhythmically, distant animal calls, insects in dry grass",
            "turn": "earth and rubble sliding, repeated dull impacts of fill against stone, wind, then thick silence",
            "after": "steady dry wind across an excavated hillside, canvas or shelter fabric moving, larks overhead",
        },
    ),
    StoryConcept(
        id_slug="angkor-wat",
        narrative_frame="abandonment",
        name="Angkor",
        category_group="Reclaimed by the Jungle",
        real_basis="Capital of the Khmer Empire in Cambodia, at its height one of the largest pre-industrial cities in the world; after the 15th century the court moved south and the forest grew over much of the temple complex.",
        environments=["a vast moated temple city with reservoirs and causeways", "wide stone terraces and processional roads under tropical sun"],
        architectures=["towered sandstone temple mountains with corbelled galleries", "long causeways, naga balustrades and reflecting barays"],
        transformations=["the city emptying, then strangler fig seedlings taking root in the roof stones and swelling into pale trunks that split the galleries apart", "forest closing over courtyards, roots pouring down walls and lifting terrace slabs"],
        camera_styles=["slow forward dolly along the causeway toward the central towers, same axis throughout", "steady rise over a gallery roof into the canopy"],
        lighting_schemes=["hot tropical sun softening into dappled green canopy light", "misty dawn light through humid air"],
        materials=["carved sandstone blocks", "laterite foundations", "pale strangler fig roots", "moss and lichen"],
        reveals=["temple doorways gripped by enormous fig roots, galleries half-swallowed, green light falling through the canopy onto carved apsaras", "stone towers standing inside the forest, roots draped over collapsed walls"],
        default_title="Angkor",
        topic_description="The Khmer capital left to the Cambodian forest after the 15th century, its temples gripped by fig roots",
        ambient_sounds={
            "before": "busy tropical temple-city ambience: water in channels, distant chanting hum without words, birds, wind in palm fronds",
            "turn": "forest ambience swelling, cicadas rising, stone cracking and grinding as roots push through, monkeys calling",
            "after": "dense jungle ambience: cicadas, dripping water, birds echoing inside stone galleries",
        },
    ),
    StoryConcept(
        id_slug="tikal",
        narrative_frame="abandonment",
        name="Tikal",
        category_group="Reclaimed by the Jungle",
        real_basis="Major Maya city in the Peten rainforest of Guatemala, dominant in the Classic period and largely abandoned by the end of the 10th century; the rainforest covered it until 19th and 20th century expeditions and excavation.",
        environments=["a wide limestone plaza between steep pyramid temples", "raised causeways crossing a cleared rainforest basin"],
        architectures=["steep-sided limestone step pyramids with roof combs", "palace ranges around plastered plazas"],
        transformations=["plazas emptying, plaster cracking, then rainforest saplings rising through the courtyards until the pyramids become forested hills", "the canopy closing until only roof combs break through the treetops"],
        camera_styles=["slow crane rise from the plaza floor to above the canopy, same move in each beat", "steady push along a causeway toward a temple stair"],
        lighting_schemes=["harsh equatorial midday over white plaster fading to deep green shade", "low mist in the basin at dawn"],
        materials=["limestone blocks and lime plaster", "flaking red pigment", "rainforest leaf litter", "buttress-rooted ceiba trees"],
        reveals=["temple roof combs emerging above an unbroken green canopy, howler monkeys in the trees below", "an excavated pyramid stair cut clean out of the forest, jungle pressing on both sides"],
        default_title="Tikal",
        topic_description="A Maya city in Guatemala abandoned by the 10th century and swallowed by rainforest",
        ambient_sounds={
            "before": "open plaza ambience: distant crowd murmur without words, drums, wind across plaster, parrots",
            "turn": "rainforest closing in: cicadas building, rain on leaves, plaster cracking, howler monkeys beginning to call",
            "after": "full rainforest ambience: howler monkeys roaring, toucans, heavy dripping canopy",
        },
    ),
    StoryConcept(
        id_slug="ciudad-perdida",
        narrative_frame="abandonment",
        name="Ciudad Perdida",
        category_group="Reclaimed by the Jungle",
        real_basis="Tayrona city in Colombia's Sierra Nevada de Santa Marta, founded around AD 800 and abandoned during the Spanish conquest era; its stone terraces were rediscovered under jungle in 1972.",
        environments=["stone terraces stepping up a steep jungle ridge above a river", "circular platforms linked by mossy stair paths"],
        architectures=["drystone circular house platforms and retaining terraces", "long stone stairways cut into the mountainside"],
        transformations=["the terraces emptying, then cloud forest advancing over every platform until the stonework disappears under moss and roots", "the mountainside returning to unbroken green, stairways vanishing beneath leaf litter"],
        camera_styles=["slow climb up the stone stairway, same ascent in each beat", "wide orbit around the terraced ridge"],
        lighting_schemes=["humid cloud-forest light with drifting mist", "bright shafts breaking through canopy gaps"],
        materials=["moss-covered drystone", "packed earth terraces", "cloud-forest ferns", "wet granite steps"],
        reveals=["circular stone terraces cleared out of the jungle on a ridge, cloud pouring between the peaks around them", "the ancient stairway exposed again, green walls of forest on either side"],
        default_title="Ciudad Perdida",
        topic_description="A Tayrona mountain city in Colombia lost to cloud forest and found again in 1972",
        ambient_sounds={
            "before": "mountain village ambience: river far below, wind on the ridge, birds, footsteps on stone",
            "turn": "rain intensifying on broad leaves, water running down terraces, forest sounds thickening",
            "after": "cloud-forest ambience: dripping water, distant river, unfamiliar bird calls, low wind",
        },
    ),
    StoryConcept(
        id_slug="ross-island",
        narrative_frame="abandonment",
        name="Ross Island",
        category_group="Reclaimed by the Jungle",
        real_basis="Administrative headquarters of the British in the Andaman Islands from 1858, with a church, ballroom and gardens; damaged by a 1941 earthquake and abandoned during the Second World War, it is now overgrown by tropical forest.",
        environments=["a manicured colonial island station with a church, gardens and sea walls", "trimmed lawns and gravel paths between brick bungalows"],
        architectures=["brick colonial church, ballroom and officers' bungalows", "arched verandas and garden walls above a tropical shore"],
        transformations=["the station emptying, then banyan roots descending over the church walls and gripping the brickwork like a net", "forest advancing across the lawns until buildings become root-covered shells"],
        camera_styles=["slow forward dolly through the church doorway, unchanged axis in each beat", "lateral track along the bungalow veranda"],
        lighting_schemes=["bright tropical island sun on white plaster fading to green filtered shade", "warm late light through leaves"],
        materials=["red brick and lime plaster", "banyan aerial roots", "tropical undergrowth", "rusted iron fittings"],
        reveals=["the roofless church completely wrapped in banyan roots, sea visible through the empty windows", "brick walls held together only by the roots that broke them"],
        default_title="Ross Island",
        topic_description="A British colonial island headquarters in the Andamans, abandoned in the 1940s and overtaken by banyan roots",
        ambient_sounds={
            "before": "colonial station ambience: sea breeze, distant band music, gravel underfoot, tropical birds",
            "turn": "monsoon rain hammering roofs, wind in palms, brick cracking, jungle insects rising",
            "after": "tropical forest ambience inside a ruin: deer barking, parakeets, wind through empty windows, surf",
        },
    ),
    StoryConcept(
        id_slug="pripyat",
        narrative_frame="abandonment",
        name="Pripyat",
        category_group="Abandoned Overnight",
        real_basis="Soviet city in Ukraine built in 1970 for Chernobyl nuclear plant workers; its roughly 49,000 residents were evacuated by bus on 27 April 1986, the day after the reactor accident, and the city was never reoccupied.",
        environments=["a modern Soviet city square with an amusement park and new apartment blocks", "wide boulevards, planted trees and a riverside promenade"],
        architectures=["prefabricated concrete apartment towers and civic halls", "a fairground with a Ferris wheel and bumper cars"],
        transformations=["the whole city emptying in a single afternoon, belongings left behind, then birch saplings breaking through asphalt year after year", "trees closing over the boulevards until the apartment blocks stand inside a forest"],
        camera_styles=["slow forward dolly across the fairground toward the Ferris wheel, same axis in each beat", "steady rise up a building facade to a rooftop view"],
        lighting_schemes=["clear spring daylight with fresh green leaves", "overcast diffused light through birch canopy"],
        materials=["precast concrete panels", "peeling yellow paint", "rusted fairground steel", "birch and poplar growth"],
        reveals=["the Ferris wheel standing in a birch forest that used to be a square, moss on the bumper cars", "apartment towers with trees growing on their roofs, roads reduced to green corridors"],
        default_title="Pripyat",
        topic_description="A Soviet city of 49,000 evacuated in a single day in 1986 and left to the forest",
        ambient_sounds={
            "before": "spring city ambience: children's fairground music, buses, birds, distant construction",
            "turn": "engines and loudspeaker tones without intelligible words, doors slamming, vehicles departing, then abrupt emptiness",
            "after": "forest reclaiming a city: wind through birches, rusted metal creaking, cuckoo and woodpecker, no traffic at all",
        },
    ),
    StoryConcept(
        id_slug="hashima",
        narrative_frame="abandonment",
        name="Hashima Island",
        category_group="Abandoned Overnight",
        real_basis="Fortified coal-mining island off Nagasaki, Japan, once among the most densely populated places on earth; the mine closed in January 1974 and the entire population left within weeks, leaving the concrete blocks to the sea.",
        environments=["a sea wall enclosing dense concrete apartment blocks on a tiny island", "narrow stairways and covered walkways between high-rise tenements"],
        architectures=["1916-era reinforced concrete apartment towers packed wall to wall", "rooftop gardens, schools and a shrine crammed onto a battleship-shaped island"],
        transformations=["the mine closing and every family leaving within weeks, then typhoons stripping windows and salt eating the concrete", "sea spray and storms hollowing the blocks until floors collapse inward"],
        camera_styles=["slow orbit around the island silhouette, same radius in each beat", "forward push down a narrow tenement stairway"],
        lighting_schemes=["flat grey maritime light with sea haze", "hard low sun behind the island silhouette"],
        materials=["salt-eroded reinforced concrete", "exposed rusting rebar", "broken window glass", "sea spray"],
        reveals=["a hollow concrete island with collapsed floors and empty window grids, waves breaking on the sea wall", "stairways ending in open air, the sea visible through every room"],
        default_title="Hashima Island",
        topic_description="A Japanese coal-mining island emptied within weeks of the mine closing in 1974",
        ambient_sounds={
            "before": "dense island-town ambience: mine machinery hum, school bell, footsteps on concrete stairs, waves against the sea wall",
            "turn": "machinery winding down to silence, ferry horn, wind rising, storm surf building",
            "after": "heavy surf on concrete, wind howling through empty window frames, loose steel banging, gulls",
        },
    ),
    StoryConcept(
        id_slug="bodie",
        narrative_frame="abandonment",
        name="Bodie",
        category_group="Abandoned Overnight",
        real_basis="California gold-rush town that peaked around 1880 with thousands of residents; the mines failed, the population drained away over decades, and the surviving buildings are preserved in a state of arrested decay.",
        environments=["a high desert main street of timber storefronts and a stamp mill", "a windswept sagebrush basin ringed by bare hills"],
        architectures=["false-fronted wooden stores, a schoolhouse and a church", "a hillside stamp mill of stacked timber and iron"],
        transformations=["the mines failing and families leaving with furniture still in the rooms, then decades of high-desert wind and snow bleaching and warping the timber", "buildings leaning, roofs sagging, paint stripping to bare grey wood"],
        camera_styles=["slow forward dolly down the main street, identical axis in each beat", "low tracking shot past a storefront window"],
        lighting_schemes=["harsh high-altitude sun with deep shadow", "cold blue winter light over snow"],
        materials=["sun-bleached pine boards", "rusted corrugated iron", "wavy window glass", "sagebrush and dust"],
        reveals=["leaning wooden storefronts still holding their goods behind dusty glass, no one on the street", "the schoolhouse with desks in place, snow drifting through a broken pane"],
        default_title="Bodie",
        topic_description="A California gold town left standing exactly as its last residents walked out",
        ambient_sounds={
            "before": "boom-town ambience: stamp mill pounding, horses and carts, piano from a saloon, wind",
            "turn": "machinery stopping, doors closing, wagons departing, wind taking over, snow beginning",
            "after": "constant high-desert wind, loose iron sheeting rattling, timber creaking, one distant crow",
        },
    ),
    StoryConcept(
        id_slug="centralia",
        narrative_frame="abandonment",
        name="Centralia",
        category_group="Abandoned Overnight",
        real_basis="Pennsylvania mining borough where a coal seam fire ignited beneath the town in 1962 and still burns; subsidence and carbon monoxide led to a government buyout in the 1980s and the near-total removal of the town.",
        environments=["a modest Appalachian mining town of clapboard homes and a church on a ridge", "streets of small houses under bare autumn trees"],
        architectures=["two-storey clapboard homes with porches", "a hilltop church and a grid of narrow residential streets"],
        transformations=["smoke seeping from cracks in gardens and roads, then houses being bought out and demolished one by one until only streets remain", "vegetation closing over empty lots while steam still rises through the cracked asphalt"],
        camera_styles=["slow forward dolly along the same residential street in each beat", "high wide shot over the town grid"],
        lighting_schemes=["cool overcast Appalachian daylight", "low autumn sun through drifting ground smoke"],
        materials=["painted clapboard", "cracked asphalt", "wet leaf litter", "rising white vapour"],
        reveals=["an empty grid of streets and driveways leading to nothing, trees filling the lots, faint smoke drifting from a fissure", "a lone set of front steps in a meadow where a house used to stand"],
        default_title="Centralia",
        topic_description="A Pennsylvania town removed above ground while a coal fire kept burning beneath it",
        ambient_sounds={
            "before": "small-town ambience: church bell, cars on wet asphalt, children distant, wind in autumn trees",
            "turn": "low subterranean rumble, hissing vents, heavy machinery demolishing structures, then quiet",
            "after": "wind across open ground, soft gas hiss from a fissure, birdsong, no traffic",
        },
    ),
    StoryConcept(
        id_slug="craco",
        narrative_frame="abandonment",
        name="Craco",
        category_group="Abandoned Overnight",
        real_basis="Medieval hilltop town in Basilicata, Italy, occupied since the 8th century; repeated landslides, worsened by a major slide in 1963, forced the population to relocate to a new town in the valley, leaving the old centre empty.",
        environments=["a stone hill town stacked around a Norman watchtower above a valley", "steep alleys and arched passages on a clay ridge"],
        architectures=["stone houses terraced up a ridge beneath a square medieval tower", "vaulted alleyways, a church and a piazza on the summit"],
        transformations=["the clay ridge slipping, walls cracking open, then the whole population moving down into the valley and the town falling silent", "wind and rain widening the cracks until roofs collapse inward"],
        camera_styles=["slow orbit around the hill town silhouette, same radius in each beat", "forward climb through an arched alley toward the tower"],
        lighting_schemes=["golden southern Italian evening light", "bare overcast light on pale clay hills"],
        materials=["pale limestone blockwork", "terracotta roof tiles", "cracked clay soil", "dry grass"],
        reveals=["a complete stone town standing empty on the ridge, roofs fallen in, not one lit window at dusk", "the tower alone above collapsed houses, valley farmland below"],
        default_title="Craco",
        topic_description="An Italian hill town evacuated after landslides and left standing empty on its ridge",
        ambient_sounds={
            "before": "Italian hill-town ambience: church bell, swifts screaming around the tower, distant voices without words, dogs",
            "turn": "deep earth movement, stone cracking, tiles sliding and shattering, vehicles leaving, then silence",
            "after": "wind through empty alleys, swifts still circling the tower, a loose shutter, distant sheep bells",
        },
    ),
    StoryConcept(
        id_slug="fordlandia",
        narrative_frame="abandonment",
        name="Fordlandia",
        category_group="Abandoned Overnight",
        real_basis="Rubber-plantation town Henry Ford built on the Tapajos River in the Brazilian Amazon from 1928, complete with American-style housing and a water tower; blight and management failures ended the project and Ford sold the land back to Brazil in 1945.",
        environments=["an American-style company town of clapboard houses beside an Amazon river", "a grid of streets with a water tower, hospital and sawmill in cleared jungle"],
        architectures=["Michigan-style clapboard bungalows with porches", "an industrial water tower, warehouses and a sawmill on the riverbank"],
        transformations=["rubber trees failing to blight, the mill going quiet, then Amazon forest advancing back across the cleared grid", "vines climbing the water tower while machinery rusts where it stopped"],
        camera_styles=["slow forward dolly along the street toward the water tower, same axis in each beat", "steady rise above the rooftops toward the river"],
        lighting_schemes=["hot equatorial sun on white clapboard", "heavy pre-storm light over the river"],
        materials=["painted clapboard siding", "riveted steel water tower", "rusting mill machinery", "advancing jungle vines"],
        reveals=["the rusted water tower standing above jungle where the streets were, roofless bungalows full of trees", "the sawmill's machinery seized in place, forest inside the building"],
        default_title="Fordlandia",
        topic_description="Henry Ford's American town in the Amazon, abandoned in 1945 and reclaimed by jungle",
        ambient_sounds={
            "before": "company-town ambience: sawmill whine, machinery, a factory whistle, river water, cicadas",
            "turn": "machinery slowing to a stop, boat engines departing, rain hammering metal roofs, jungle insects surging",
            "after": "Amazon forest ambience: cicadas, howler monkeys, rain on rusted steel, river current",
        },
    ),
    StoryConcept(
        id_slug="petra",
        narrative_frame="abandonment",
        name="Petra",
        category_group="Carved from Stone",
        real_basis="Nabataean caravan capital in Jordan, carved into sandstone cliffs and prosperous around the 1st century BC to 1st century AD; earthquakes, notably in AD 363 and 551, and shifting trade routes reduced it to a local settlement until European rediscovery in 1812.",
        environments=["a thriving caravan city in a red sandstone canyon", "a colonnaded street between cliff-carved facades and market stalls"],
        architectures=["monumental facades cut directly into sandstone cliffs", "a colonnaded street, theatre and rock-cut tombs"],
        transformations=["earthquakes shearing columns and cracking the facades, then trade routes shifting away and the city emptying", "flash floods burying the street in sand and rubble until only the carved fronts remain visible"],
        camera_styles=["slow forward dolly out of the narrow siq toward the great facade, same reveal in each beat", "steady lateral track along the colonnaded street"],
        lighting_schemes=["narrow shafts of sunlight in a deep red canyon", "warm late sun turning the sandstone deep orange"],
        materials=["banded red sandstone", "carved column capitals", "flood-deposited sand", "desert scrub"],
        reveals=["the carved facade standing alone at the canyon mouth, street level buried metres deep in sand", "empty rock-cut tombs in a silent canyon, no city left in front of them"],
        default_title="Petra",
        topic_description="A Nabataean caravan capital in Jordan, shaken by earthquakes and left to the desert canyon",
        ambient_sounds={
            "before": "caravan-city ambience: camels, market murmur without words, hammering stone, water channels running",
            "turn": "deep earthquake rumble, columns toppling, stone dust settling, then flash-flood water rushing through the canyon",
            "after": "canyon wind, sand hissing on stone, echoing bird calls high in the cliff walls",
        },
    ),
    StoryConcept(
        id_slug="derinkuyu",
        narrative_frame="abandonment",
        name="Derinkuyu",
        category_group="Carved from Stone",
        real_basis="Multi-level underground city in Cappadocia, Turkiye, carved into soft volcanic tuff and expanded over centuries; it could shelter thousands with ventilation shafts, wells and rolling stone doors, and was rediscovered in 1963 behind a house wall.",
        environments=["a Cappadocian plateau of soft tuff and rock-cut villages above ground", "torch-lit tunnels descending level after level beneath the fields"],
        architectures=["carved tunnel networks with stables, chapels and wells over eight levels", "circular rolling stone doors sealing each passage"],
        transformations=["families descending with livestock and sealing the rolling stone doors behind them, then the passages falling out of use and being walled up", "the entrances disappearing under houses and fields until the city below is forgotten"],
        camera_styles=["slow forward creep down a descending tunnel, same descent in each beat", "steady push toward a rolling stone door"],
        lighting_schemes=["warm flickering torchlight against pale tuff", "single cold shaft of daylight from a ventilation column"],
        materials=["carved volcanic tuff", "soot-blackened ceilings", "stone millstone doors", "packed earth floors"],
        reveals=["empty carved chambers eight levels deep, ventilation shafts dropping light into darkness, no sound at all", "the rolling stone door standing open on an abandoned passage"],
        default_title="Derinkuyu",
        topic_description="A Cappadocian underground city carved for thousands, sealed up and forgotten until 1963",
        ambient_sounds={
            "before": "underground settlement ambience: livestock in stone stables, dripping water, low echoing murmur, torch flames",
            "turn": "the grinding roll of a great stone door closing, echoes dying away, footsteps receding upward",
            "after": "absolute underground stillness: slow water drips, faint air moving in a ventilation shaft, deep echo",
        },
    ),
    StoryConcept(
        id_slug="mesa-verde",
        narrative_frame="abandonment",
        name="Mesa Verde",
        category_group="Carved from Stone",
        real_basis="Ancestral Puebloan cliff dwellings in Colorado, built into canyon alcoves in the 1190s and occupied for less than a century before the population migrated south in the late 13th century, during a period of severe drought.",
        environments=["a sandstone alcove village built into a canyon wall", "green mesa-top farm plots above a deep canyon"],
        architectures=["multi-storey masonry rooms and round kivas set inside a rock alcove", "ladders and hand-and-toe trails linking cliff to mesa top"],
        transformations=["crops failing through years of drought, then the families climbing out and moving south, leaving pots and grinding stones in place", "the alcove falling silent as dust settles over the rooms"],
        camera_styles=["slow forward dolly into the alcove from the canyon air, same approach in each beat", "steady lateral track across the dwelling face"],
        lighting_schemes=["warm reflected canyon light inside the alcove", "hard high-desert sun on the opposite canyon wall"],
        materials=["sandstone block masonry", "mud mortar", "juniper roof beams", "red canyon dust"],
        reveals=["the cliff village intact and completely empty in its alcove, ladders gone, canyon silent below", "round kivas open to the sky, grinding stones still set in the floors"],
        default_title="Mesa Verde",
        topic_description="Colorado cliff dwellings built in the 1190s and left behind within a century",
        ambient_sounds={
            "before": "cliff-village ambience: grinding stone on stone, turkeys, children distant without words, wind across the canyon",
            "turn": "dry wind strengthening, loose dust, ladders being drawn up, footsteps fading on rock",
            "after": "canyon wind through empty rooms, ravens echoing off the walls, absolute human silence",
        },
    ),
    StoryConcept(
        id_slug="ani",
        narrative_frame="abandonment",
        name="Ani",
        category_group="Carved from Stone",
        real_basis="Medieval Armenian capital on the Turkiye-Armenia border, said to have held over 100,000 people around AD 1000; sacked in 1064, devastated by an earthquake in 1319 and bypassed by trade, it was gradually abandoned and stands empty on the plateau.",
        environments=["a walled medieval city of churches on a grassy plateau above a river gorge", "cathedral domes and city walls under a wide Anatolian sky"],
        architectures=["Armenian cathedral and round churches in red and black tuff", "double city walls with round towers above a ravine"],
        transformations=["the 1319 earthquake shearing domes and collapsing naves, then trade routes shifting and the population draining away", "grass advancing across the streets until only churches stand on open steppe"],
        camera_styles=["slow orbit around the cathedral on the plateau, same radius in each beat", "forward dolly through the city gate toward the churches"],
        lighting_schemes=["long low steppe light with racing cloud shadow", "cold clear high-plateau daylight"],
        materials=["red and black volcanic tuff", "carved blind arcading", "steppe grass", "collapsed rubble"],
        reveals=["isolated churches standing in open grassland where a city of 100,000 stood, gorge cutting behind them", "a cathedral with half its dome gone, sky visible through the nave, nothing else left standing"],
        default_title="Ani",
        topic_description="A medieval Armenian capital of 100,000 reduced to churches standing alone on the steppe",
        ambient_sounds={
            "before": "medieval city ambience: church bells, market murmur without words, horses, wind on the plateau",
            "turn": "deep earthquake rumble, masonry collapsing, dust, then wind rising over the ruins",
            "after": "constant steppe wind through empty churches, distant river in the gorge, larks, no human sound",
        },
    ),
    StoryConcept(
        id_slug="lalibela",
        narrative_frame="creation",
        name="Lalibela",
        category_group="Carved from Stone",
        real_basis="Eleven medieval churches in Ethiopia carved downward directly out of solid volcanic rock, traditionally attributed to King Lalibela in the 12th and 13th centuries; they remain in active religious use.",
        environments=["a red volcanic highland plateau with trenches cut into the bedrock", "connected rock trenches and tunnels between sunken courtyards"],
        architectures=["monolithic churches carved downward from the rock, freestanding within their pits", "rock-cut tunnels, drainage channels and cruciform roofs at ground level"],
        transformations=["masons cutting downward into the bedrock, trench by trench, until a church stands free inside its own pit", "the rock roof emerging first as a cross at ground level, then walls and windows appearing beneath it"],
        camera_styles=["slow crane descent from the ground-level roof into the surrounding trench, same move in each beat", "steady orbit around the freestanding church inside its pit"],
        lighting_schemes=["hard highland sun with deep trench shadow", "warm low light on red rock walls"],
        materials=["red scoria volcanic rock", "chiselled rock faces", "worn stone thresholds", "highland dust"],
        reveals=["a complete cross-roofed church standing free in a deep pit cut from one piece of rock, pilgrims' paths worn into the stone", "sunken courtyards linked by tunnels, every surface cut rather than built"],
        default_title="Lalibela",
        topic_description="Ethiopian churches carved downward out of solid rock in the 12th and 13th centuries",
        ambient_sounds={
            "before": "highland plateau ambience: wind, chisels ringing on rock steadily, distant livestock, birds",
            "turn": "sustained rhythmic stone cutting, rock fragments falling, dust, the sound deepening as the trench cuts down",
            "after": "resonant echo inside a rock trench, wind, distant chanting hum without words, footsteps on worn stone",
        },
    ),
    StoryConcept(
        id_slug="aral-sea",
        narrative_frame="vanishing",
        name="The Aral Sea",
        category_group="Lost to the Water",
        real_basis="Once the fourth-largest lake in the world, the Aral Sea in Central Asia shrank drastically after Soviet irrigation projects diverted its feeder rivers from the 1960s; former ports were left tens of kilometres from any water, stranding fishing fleets on dry seabed.",
        environments=["a busy inland sea port with fishing trawlers at the quay", "open blue water reaching to the horizon behind a harbour town"],
        architectures=["concrete quays, cranes and a fish cannery", "steel fishing trawlers moored along the waterfront"],
        transformations=["the shoreline retreating year after year, quays left standing above dry ground, trawlers settling onto sand", "the seabed emerging as salt flats and scrub while the water withdraws beyond the horizon"],
        camera_styles=["locked wide shot from the quay toward the horizon, framing unchanged in every beat", "slow forward dolly past a beached trawler hull"],
        lighting_schemes=["clear bright maritime light on open water", "hazy dust-laden light over salt flats"],
        materials=["rusting steel hulls", "cracked salt crust", "concrete quay blocks", "dry desert scrub"],
        reveals=["fishing trawlers sitting upright on sand with camels walking past, the sea nowhere in sight", "a harbour crane standing over dry salt flats stretching to the horizon"],
        default_title="The Aral Sea",
        topic_description="A port fleet left stranded on dry seabed as one of the world's largest lakes withdrew",
        ambient_sounds={
            "before": "working harbour ambience: water slapping hulls, gulls, diesel engines, winches, rigging",
            "turn": "water sounds thinning and receding, hulls grounding and creaking, wind picking up over exposed ground",
            "after": "dry desert wind over salt flats, loose steel groaning, sand against metal, no water at all",
        },
    ),
    StoryConcept(
        id_slug="salton-sea",
        narrative_frame="vanishing",
        name="The Salton Sea",
        category_group="Lost to the Water",
        real_basis="California lake created accidentally in 1905 when Colorado River water breached an irrigation canal; it became a popular resort area in the 1950s and 60s, then rising salinity and agricultural runoff collapsed the fishery and the shoreline resorts were abandoned.",
        environments=["a mid-century desert resort shoreline with marinas and motels", "yacht clubs and palm-lined promenades on a bright inland sea"],
        architectures=["mid-century modern motels, a yacht club and boat ramps", "beachfront cabanas and neon roadside signs"],
        transformations=["salinity rising until the fish die off, then the resorts closing and the shoreline retreating into salt crust", "buildings stripped and drowned in dust while the beach turns to bone-coloured crust"],
        camera_styles=["slow forward dolly along the boat ramp toward the water, same axis in each beat", "steady lateral track past the motel frontage"],
        lighting_schemes=["saturated desert resort sunlight", "hazy pale light over a dusty shoreline"],
        materials=["mid-century pastel stucco", "sun-cracked concrete", "salt and fish-bone beach crust", "rusted neon frames"],
        reveals=["a boat ramp ending on dry salt crust hundreds of metres from the water, motel shells behind it", "a yacht club standing empty above a white beach made of salt and bone"],
        default_title="The Salton Sea",
        topic_description="A California desert resort built on an accidental lake, abandoned as the water turned to salt",
        ambient_sounds={
            "before": "resort shoreline ambience: outboard motors, water lapping, distant mid-century radio music, gulls, laughter without words",
            "turn": "motors fading out, wind rising over flat water, buildings emptying, doors banging",
            "after": "dry hot wind over salt crust, loose metal signage creaking, crust crunching, almost no birds",
        },
    ),
    StoryConcept(
        id_slug="nan-madol",
        narrative_frame="abandonment",
        name="Nan Madol",
        category_group="Lost to the Water",
        real_basis="Ceremonial complex in Micronesia built on nearly 100 artificial islets from stacked columnar basalt logs, constructed mainly between the 13th and 17th centuries; it was abandoned by around 1800 and the canals and walls now stand in tidal mangrove water.",
        environments=["a network of artificial stone islets and tidal canals in a lagoon", "high basalt walls rising straight from turquoise water"],
        architectures=["walls of stacked hexagonal basalt columns laid like logs", "islet platforms, tombs and canal-side landings"],
        transformations=["the complex falling out of use, then mangrove roots seizing the walls while tides work at the foundations", "canals silting and the basalt walls tilting as the sea keeps rising against them"],
        camera_styles=["slow forward glide along a canal between the walls, same passage in each beat", "steady rise above the islet grid to reveal the lagoon"],
        lighting_schemes=["bright equatorial light on turquoise water", "green filtered light beneath mangrove canopy"],
        materials=["hexagonal basalt columns", "coral rubble fill", "mangrove roots", "tidal water"],
        reveals=["basalt walls standing in tidal water with mangroves growing through them, canals empty of any boat", "the stacked stone columns leaning above the lagoon, reef visible beyond"],
        default_title="Nan Madol",
        topic_description="A Pacific stone city of basalt islets, abandoned around 1800 and standing in tidal water",
        ambient_sounds={
            "before": "lagoon ceremonial ambience: paddles in water, distant drums, wind in palms, reef surf beyond",
            "turn": "tide rising against stone, mangroves creaking, rain on water, activity sounds fading out",
            "after": "tidal lapping against basalt, mangrove roots ticking, reef surf, tropical birds, no human sound",
        },
    ),
    StoryConcept(
        id_slug="machu-picchu",
        narrative_frame="abandonment",
        name="Machu Picchu",
        category_group="Above the Clouds",
        real_basis="Inca royal estate built in the mid-15th century on a ridge in Peru and abandoned about a century later around the time of the Spanish conquest; never found by the Spanish, it was brought to international attention in 1911.",
        environments=["a terraced Inca estate on a knife-edge ridge between cloud-forest peaks", "agricultural terraces stepping down a mountainside above a river gorge"],
        architectures=["fitted ashlar stone buildings, temples and a sundial stone", "stepped agricultural terraces and stone water channels"],
        transformations=["the estate emptying within a century, then cloud forest advancing over the terraces until the ridge looks like unbroken green", "vegetation covering the walls while the stonework beneath stays perfectly fitted"],
        camera_styles=["slow crane rise along the ridge to the classic overlook, same move in each beat", "steady forward dolly through a stone doorway toward the peak"],
        lighting_schemes=["cloud pouring over the ridge in bright morning light", "cool blue mountain shade with sun breaking through"],
        materials=["precisely fitted granite ashlar", "terrace retaining stone", "cloud-forest grass and moss", "wet granite"],
        reveals=["the complete stone estate on its ridge with cloud moving through the empty plazas, mountains dropping away on both sides", "terraces cleared again, every joint in the granite still tight after five centuries"],
        default_title="Machu Picchu",
        topic_description="An Inca royal estate on a Peruvian ridge, abandoned within a century and hidden by cloud forest",
        ambient_sounds={
            "before": "high-altitude estate ambience: wind over the ridge, water running in stone channels, llamas, distant river far below",
            "turn": "wind and rain increasing, vegetation rustling, human sounds thinning to nothing",
            "after": "thin mountain wind through empty stone doorways, cloud moving, Andean birds, the river far below",
        },
    ),
    StoryConcept(
        id_slug="rapa-nui",
        narrative_frame="creation",
        name="Rapa Nui",
        category_group="Carved from Stone",
        real_basis="Remote Pacific island settled by Polynesians, whose people carved nearly 900 monumental moai statues, mostly between roughly AD 1250 and 1500; hundreds of unfinished statues remain in the Rano Raraku quarry where carving stopped.",
        environments=["a volcanic quarry slope crowded with statues in every stage of carving", "grass headlands above the Pacific with statue platforms facing inland"],
        architectures=["monumental basalt-tuff moai on stone ahu platforms", "an open quarry face with half-cut statues still attached to the bedrock"],
        transformations=["carving stopping mid-work, chisels set down, statues left attached to the rock face", "grass creeping up the standing statues until they are buried to the shoulders"],
        camera_styles=["slow lateral track across the quarry face, same pass in each beat", "steady low push toward a statue head rising from the grass"],
        lighting_schemes=["bright oceanic light with fast cloud", "low golden light raking across the quarry slope"],
        materials=["volcanic tuff", "basalt tools", "island grass", "sea spray"],
        reveals=["dozens of statues standing buried to the shoulders in grass, one still lying unfinished and attached to the quarry rock", "the quarry slope covered in half-carved figures, work stopped mid-cut"],
        default_title="Rapa Nui",
        topic_description="A Pacific island quarry where hundreds of moai were left unfinished exactly where carving stopped",
        ambient_sounds={
            "before": "quarry ambience: stone tools striking tuff in rhythm, wind off the ocean, distant surf, seabirds",
            "turn": "the carving sounds thinning and stopping one by one, wind rising, grass moving",
            "after": "constant ocean wind across grass, distant surf on cliffs, seabirds, complete absence of tools",
        },
    ),
    StoryConcept(
        id_slug="surtsey",
        narrative_frame="creation",
        name="Surtsey",
        category_group="Born from the Sea",
        real_basis="Volcanic island off southern Iceland formed by an eruption that began on the seafloor in November 1963 and continued until 1967; it has been protected since its formation as a natural laboratory for how life colonises new land.",
        environments=["open North Atlantic swell with nothing above the water", "grey ocean under low Icelandic cloud"],
        architectures=["a rising volcanic cone of black ash and lava", "new sea cliffs and a black sand shoreline"],
        transformations=["the sea boiling and exploding upward in black ash plumes, then a cone breaking the surface and hardening into rock", "lava flows armouring the new coast while waves cut cliffs into it"],
        camera_styles=["locked wide shot on the same patch of sea in every beat, the island rising into frame", "slow orbit around the emerging cone"],
        lighting_schemes=["stormy North Atlantic light with steam and ash", "clear cold northern light on black rock"],
        materials=["black volcanic ash", "cooled basalt lava", "sea foam", "first mosses and grasses"],
        reveals=["a solid black island with cliffs, a green fringe of moss and nesting seabirds where open ocean was sixty years ago", "the cone at rest, waves breaking on new basalt, life already taking hold"],
        default_title="Surtsey",
        topic_description="An Icelandic island that rose out of the open ocean in 1963 and is now colonised by life",
        ambient_sounds={
            "before": "open ocean ambience: heavy swell, wind, distant seabirds, nothing else",
            "turn": "violent underwater detonations, steam explosions, ash raining on water, hissing lava meeting sea",
            "after": "waves on new black rock, wind over ash, growing seabird colony calls",
        },
    ),
]


def get_story_concept(id_slug: str):
    """Returns the StoryConcept with this slug, or None."""
    return next((c for c in STORY_CONCEPTS if c.id_slug == id_slug), None)
